### ISSUE TITLE
src > windows: current repo state is normalized to AMD64 format

### ISSUE THREAD

**Issue by dwolner** [sqli/sqli-cordova-disk-space-plugin#1]
the current repo state for the windows platform is normalized to AMD64 format, but I need to be able to build to all formats (any CPU).

**Comment by dwolner** [comment]
I was able to open the Visual Studio solution and build as anycpu and replaced the .winmd file with that. now it works with all formats on windows 10. would this be helpful to include?

**Comment by gigaga** [comment]
Yes. Indeed, it is a better like this. Please, submit your pull request.

**Comment by gigaga** [comment]
Done by the pull request
