### ISSUE TITLE
building for Windows 10 store failed because of file within DiskSpaceLibrary

### ISSUE THREAD

**Issue by dwolner** [sqli/sqli-cordova-disk-space-plugin#3]
When submitting to the Windows store, my app did not pass one specific test:
![screenshot 2016-06-15 16 39 10](https://cloud.githubusercontent.com/assets/8670637/16101091/c9e3ce88-3317-11e6-9d00-cd19798ab750.jpg)

How do I empty the resources file? Or does somebody know whats going on here?

**Comment by gigaga** [comment]
Hi, 

I think the problem is caused by the file DiskSpaceLibrary.rd.xml. Can you try to rebuild winmd file without this file?

**Comment by dwolner** [comment]
Sorry, I never got back around to testing this solution. Will try building for production.

**Comment by gigaga** [comment]
To close!
